# Generated by Django 4.1 on 2022-08-13 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_comment',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
