# Generated by Django 4.1 on 2022-09-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_holiday_shopping_alter_task_task_completed_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
