# Generated by Django 4.1 on 2022-09-24 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complete',
        ),
    ]
